### ISSUE TITLE
ACT time in mission plan not saved, not reflected in subsequent waypoints

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#22] opened 2020-11-22 16:56 UTC
See title. Refers to WP 3 and subsequent waypoints.

![Screenshot 2020-11-22 175412](https://user-images.githubusercontent.com/35634100/99909974-ce006080-2ceb-11eb-9633-550433ee086f.png)

![Screenshot 2020-11-22 175428](https://user-images.githubusercontent.com/35634100/99909976-d2c51480-2ceb-11eb-9cbd-7320e35c3f1e.png)

**Comment by jkhoel** [comment] 2020-11-23 07:37
I noticed this also applies to ALT and GS. I tested a little bit on my MDC yesterday, and it seems if the value does not change, it will not get repeated when printed?

**Comment by martinco** [comment] 2020-11-23 11:39
I see a few issues here:

* The ACT issue you presented
  * I can't seem to re-create the issue
  * The WP TOT updates happen on "changed" event from the input - The only thing I can really do would be to add an additional pre-save check to catch in the event it did not fire (and seems a sensible thing to do) 
* The declutter should remove repeated GS / ALT when they're the same as before (i.e: WP3 should be blank)

@jkhoel that's the intended behavior

**Comment by martinco** [comment] 2020-11-23 11:53
The template declutter step was a noob mistake I just fixed in 213b23ed42ce39bcdc39cbe6b097ba0c8ac372fc, will look into the TOT issue now / try and reliably re-create it to ensure a pre-save validation step caters for that sequence of events

**Closed as completed** 2020-11-23 13:20 UTC

**Comment by steven-omaha** [comment] 2020-11-23 14:34
Thanks for the quick fix! Great job! :)
